### ISSUE TITLE
The Application breaks in the landscape mode.

### ISSUE THREAD

**Issue by JoyKrishan** [JoyKrishan/BMI-Calculator-flutter#1]
The app runs perfectly in the portrait mode but when the screen is rotated the button overflows? Should the app be created differently for different orientations?

**Comment by ronydebnath** [comment]
Yes, The app design varies in different orientation. 
You can use `OrientationBuilder ` Widget to adjust the buttons or other elements while in landscape mode.
A basic example is explained here: https://flutter.dev/docs/cookbook/design/orientation
